### ISSUE TITLE
@@ in strings

### ISSUE THREAD

**Issue by tonnyavery** [pandawarrior91/android-string-parser#4]
All ',' are replaced with '@@' during conversion to CSV, but never replaced back to ',' in the resulting CSV file.

**Comment by LiewJunTung** [comment]
It's fixed in the latest commit, 13b3faba9347a7f0993f7dad6e92910bcc534cb9.
Made it so that it will support commas now convert XML to CSV and vice versa. The IntelliJ plugin update should be online in a few days.

You try with the main app while you waiting for the plugin to be online [here](https://github.com/pandawarrior91/Android-strings-xml-csv-converter/releases/tag/v1.2.0)
Do tell me if there's anything wrong.
Thanks for your interest and heads up! :+1:
